### PR TITLE
Use gpg2 instead of old gpg1

### PR DESCRIPTION
**Pull request by ip1981**
Partially addresses https://github.com/AGWA/git-crypt/issues/65

### CODE REVIEW

**Comment by mathieujobin** [comment]
what when GPG3 comes out ? 

on my system (archlinux), gpg is a symlink to gpg2

**Comment by mathieujobin** [comment]
I think it's a matter of time until the rename gpg2 back to gpg
they must give some time for older systems to die or something

**Comment by ip1981** [comment]
Actually, the key part is linking to GPG2 from Nix store. And GPG2 can use Pinentry and other cool stuff :-) I'd refrain from hacking git-crypt now, because its build system is plain Makefile.

**Comment by ip1981** [comment]
> what when GPG3 comes out?

it definitely won't be called `gpg` ;-)

**Comment by ip1981** [comment]
Oh, I was sure I was commenting https://github.com/NixOS/nixpkgs/pull/11749 :-D

**Comment by ip1981** [comment]
GPG1 is still alive: GnuPG 1.4.19 released (2015-02-27) 
And we have been using GPG2 for almost a decade: GnuPG 2.0 released (2006-11-13 12:43:16)

¯\_(ツ)_/¯

**Comment by smemsh** [comment]
I think this only hardcodes a different name, although it's realistic, but a runtime way (one of env, rc, command line) maybe better.

this might be handled instead with a diversion in the package manager for distributions until it's accessible with a file or something the package installation script can create without having to modify the build (IMO)

gpg2 may eventually be called gpg, it's possible... maybe it's small / split up enough at some point to embed like gpg1 is still used for, removing the need.

**Pull request closed without merging**
