### PR TITLE
crypto: fix for compatibility with openssl 1.1

### LINKED ISSUE #111: Getting build error while building git-crypt on a docker based on ubuntu:14.04
```g++
g++ -Wall -pedantic -Wno-long-long -O2 -Wno-deprecated-declarations   -c -o crypto-openssl.o crypto-openssl.cpp
crypto-openssl.cpp:74:11: error: field ‘ctx’ has incomplete type ‘HMAC_CTX {aka hmac_ctx_st}’
  HMAC_CTX ctx;
           ^~~
In file included from /usr/include/openssl/evp.h:14:0,
                 from /usr/include/openssl/hmac.h:15,
                 from crypto-openssl.cpp:36:
/usr/include/openssl/ossl_typ.h:102:16: note: forward declaration of ‘HMAC_CTX {aka struct hmac_ctx_st}’
 typedef struct hmac_ctx_st HMAC_CTX;
                ^~~~~~~~~~~
crypto-openssl.cpp: In destructor ‘Hmac_sha1_state::~Hmac_sha1_state()’:
crypto-openssl.cpp:88:27: error: ‘HMAC_cleanup’ was not declared in this scope
  HMAC_cleanup(&(impl->ctx));
                           ^
<builtin>: recipe for target 'crypto-openssl.o' failed
```
Unfortunately I am not quite sure how to track down a fix.

### PR DESCRIPTION
**Pull request by kalbasit**
closes #111

### CODE REVIEW

**Comment by awitherow** [comment]
Can this be merged already?

**Comment by kalbasit** [comment]
@awitherow I don't have write permission to do so :(

**Comment by awitherow** [comment]
I will try and poke the maintainer.

**Comment by awitherow** [comment]
@AGWA are you there? Ping ping.

**Comment by AGWA** [comment]
I'm curious if there are any platforms currently shipping _only_ OpenSSL 1.1 and not also OpenSSL 1.0.  There are definitely platforms that still only have OpenSSL 1.0, and git-crypt needs to continue supporting them.  So I'm afraid it's not as simple as just merging this PR.

**Comment by kalbasit** [comment]
@AGWA do you know if there's a way to split the build? perhaps with a `#ifdef` or maybe we can do so in the Makefile?

**Comment by AGWA** [comment]
Yeah, `#ifdef` would work.  Does OpenSSL define any constants in its header files that we could match on?

**Comment by kalbasit** [comment]
@AGWA openssl 1.1 defines `OPENSSL_API_COMPAT` but openssl 1.0 does not. See https://github.com/openssl/openssl/blob/master/include/openssl/opensslconf.h.in#L93

feel free to push on my PR if you have a system with openssl 1.0 handy you can test with.

**Comment by kalbasit** [comment]
@AGWA I updated the PR, split the crypto into two files. We could merge into one with multiple ifs, but this might be cleaner in the long run. @AGWA let me know if this is acceptable to you and I'll squash my commits for you.

**Comment by AGWA** [comment]
@kalbasit Thanks for updating the PR.  Doesn't the Makefile also need to be updated so the new file you added will be compiled?

**Comment by kalbasit** [comment]
@AGWA You're right. I just pushed a build fix. Is there a test suite we can run?

**Pull request closed without merging**
